[build]
builder = "nixpacks"

[deploy]
startCommand = "cd master && python server.py"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
